create table if not exists public.fichas_venda (
  id bigint generated by default as identity primary key,
  data_contrato date,
  prazo_servico date,
  nome_cliente text not null,
  numero_ficha integer check (numero_ficha > 0),
  terceiros text,
  telefone_terceiros text,
  email_terceiros text,
  telefones text,
  endereco text,
  numero_endereco text,
  complemento_endereco text,
  cep text,
  municipio text,
  uf text,
  cpf_cnpj text,
  cpf_normalizado text,
  cnh text,
  data_nascimento date,
  data_primeira_cnh date,
  nacionalidade text,
  estado_civil text,
  profissao text,
  email text,
  nome_consultor text,
  origem text,
  sne text,
  forma_pagamento text,
  banco text,
  pagamentos jsonb not null default '[]'::jsonb,
  valor_total numeric(12, 2),
  valor_entrada numeric(12, 2),
  valor_restante numeric(12, 2),
  observacao_valor_restante text,
  clausula_adicional text,
  instancia_processo text,
  tipo_processo text,
  numero_processo text,
  prazo_processo date,
  prazos_processo_texto text,
  visto_juridico text,
  assinatura_visto_juridico text,
  tipo_outro_servico text,
  poderes_outro_servico text,
  multas_processo text,
  instancia_multa text,
  auto_detran text,
  auto_renainf text,
  tipo_multa text,
  placa text,
  placa_proprietario text,
  cpf_proprietario text,
  renavam text,
  prazo_multa date,
  prazos_multa_texto text,
  visto_juridico_multa text,
  processo_vinculado_multa text,
  observacoes text,
  data_envio timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by_consultor_id text,
  updated_by_consultor_id text
);

create index if not exists fichas_venda_cpf_normalizado_idx
on public.fichas_venda (cpf_normalizado);

alter table public.fichas_venda
add column if not exists numero_ficha integer,
add column if not exists numero_endereco text,
add column if not exists complemento_endereco text,
add column if not exists pagamentos jsonb not null default '[]'::jsonb,
add column if not exists prazos_processo_texto text,
add column if not exists prazos_multa_texto text,
add column if not exists placa_proprietario text,
add column if not exists cpf_proprietario text,
add column if not exists multas_processo text,
add column if not exists processo_vinculado_multa text,
add column if not exists observacao_valor_restante text,
add column if not exists clausula_adicional text,
add column if not exists nacionalidade text,
add column if not exists estado_civil text,
add column if not exists profissao text,
add column if not exists municipio text,
add column if not exists uf text,
add column if not exists tipo_outro_servico text,
add column if not exists poderes_outro_servico text;

create unique index if not exists fichas_venda_cpf_numero_ficha_uidx
on public.fichas_venda (
  (coalesce(nullif(cpf_normalizado, ''), nullif(regexp_replace(coalesce(cpf_cnpj, ''), '\D', '', 'g'), ''))),
  numero_ficha
)
where numero_ficha is not null
  and coalesce(nullif(cpf_normalizado, ''), nullif(regexp_replace(coalesce(cpf_cnpj, ''), '\D', '', 'g'), '')) is not null;

create or replace function public.assign_ficha_number()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  cpf_key text;
begin
  cpf_key := coalesce(
    nullif(new.cpf_normalizado, ''),
    nullif(regexp_replace(coalesce(new.cpf_cnpj, ''), '\D', '', 'g'), '')
  );

  if cpf_key is null then
    new.numero_ficha := coalesce(new.numero_ficha, 1);
    return new;
  end if;

  perform pg_advisory_xact_lock(hashtext(cpf_key));

  select coalesce(max(numero_ficha), 0) + 1
  into new.numero_ficha
  from public.fichas_venda
  where coalesce(
    nullif(cpf_normalizado, ''),
    nullif(regexp_replace(coalesce(cpf_cnpj, ''), '\D', '', 'g'), '')
  ) = cpf_key;

  return new;
end;
$$;

drop trigger if exists assign_ficha_number on public.fichas_venda;

create trigger assign_ficha_number
before insert on public.fichas_venda
for each row
execute function public.assign_ficha_number();

alter table public.fichas_venda enable row level security;

drop policy if exists "service role can manage fichas_venda" on public.fichas_venda;

create policy "service role can manage fichas_venda"
on public.fichas_venda
as permissive
for all
to service_role
using (true)
with check (true);

create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  nome_responsavel text not null,
  email text not null unique,
  telefone text not null,
  nivel_acesso text not null check (nivel_acesso in ('admin', 'consultor', 'andamento')),
  ativo boolean not null default true,
  must_change_password boolean not null default false,
  password_plain text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create or replace function public.set_user_profiles_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;

create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row
execute function public.set_user_profiles_updated_at();

alter table public.user_profiles enable row level security;

drop policy if exists "service role can manage user_profiles" on public.user_profiles;

create policy "service role can manage user_profiles"
on public.user_profiles
as permissive
for all
to service_role
using (true)
with check (true);

create table if not exists public.access_codes (
  id uuid primary key default gen_random_uuid(),
  nome_responsavel text not null,
  codigo_acesso text not null unique,
  nivel_acesso text not null check (nivel_acesso in ('admin', 'consultor', 'andamento')),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_templates (
  key text primary key,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('ficha', 'document_template')),
  entity_id text not null,
  entity_label text not null,
  action text not null,
  summary text not null,
  actor_id text not null,
  actor_name text not null,
  details jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.access_codes (
  nome_responsavel,
  codigo_acesso,
  nivel_acesso,
  ativo
)
values (
  'Administrador',
  'ADMIN123',
  'admin',
  true
)
on conflict (codigo_acesso) do nothing;
