create table if not exists public.fichas_venda (
  id bigint generated by default as identity primary key,
  data_contrato date,
  prazo_servico date,
  nome_cliente text not null,
  terceiros text,
  telefones text,
  endereco text,
  cep text,
  cpf_cnpj text,
  cpf_normalizado text,
  cnh text,
  data_nascimento date,
  data_primeira_cnh date,
  email text,
  nome_consultor text,
  origem text,
  sne text,
  forma_pagamento text,
  banco text,
  valor_total numeric(12, 2),
  valor_entrada numeric(12, 2),
  valor_restante numeric(12, 2),
  instancia_processo text,
  tipo_processo text,
  numero_processo text,
  prazo_processo date,
  visto_juridico text,
  assinatura_visto_juridico text,
  instancia_multa text,
  auto_detran text,
  auto_renainf text,
  tipo_multa text,
  placa text,
  renavam text,
  prazo_multa date,
  visto_juridico_multa text,
  observacoes text,
  data_envio timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by_consultor_id text,
  updated_by_consultor_id text
);

create index if not exists fichas_venda_cpf_normalizado_idx
on public.fichas_venda (cpf_normalizado);

alter table public.fichas_venda enable row level security;

drop policy if exists "service role can manage fichas_venda" on public.fichas_venda;

create policy "service role can manage fichas_venda"
on public.fichas_venda
as permissive
for all
to service_role
using (true)
with check (true);
