create table if not exists public.fichas_venda (
  id bigint generated by default as identity primary key,
  data_contrato date,
  prazo_servico date,
  nome_cliente text not null,
  terceiros text,
  telefones text,
  endereco text,
  cep text,
  municipio text,
  uf text,
  cpf_cnpj text,
  cpf_normalizado text,
  cnh text,
  data_nascimento date,
  data_primeira_cnh date,
  nacionalidade text,
  estado_civil text,
  profissao text,
  email text,
  nome_consultor text,
  origem text,
  sne text,
  forma_pagamento text,
  banco text,
  valor_total numeric(12, 2),
  valor_entrada numeric(12, 2),
  valor_restante numeric(12, 2),
  observacao_valor_restante text,
  clausula_adicional text,
  instancia_processo text,
  tipo_processo text,
  numero_processo text,
  prazo_processo date,
  visto_juridico text,
  assinatura_visto_juridico text,
  multas_processo text,
  instancia_multa text,
  auto_detran text,
  auto_renainf text,
  tipo_multa text,
  placa text,
  placa_proprietario text,
  cpf_proprietario text,
  renavam text,
  prazo_multa date,
  visto_juridico_multa text,
  processo_vinculado_multa text,
  observacoes text,
  data_envio timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by_consultor_id text,
  updated_by_consultor_id text
);

create index if not exists fichas_venda_cpf_normalizado_idx
on public.fichas_venda (cpf_normalizado);

alter table public.fichas_venda
add column if not exists placa_proprietario text,
add column if not exists cpf_proprietario text,
add column if not exists multas_processo text,
add column if not exists processo_vinculado_multa text,
add column if not exists observacao_valor_restante text,
add column if not exists clausula_adicional text,
add column if not exists nacionalidade text,
add column if not exists estado_civil text,
add column if not exists profissao text,
add column if not exists municipio text,
add column if not exists uf text;

alter table public.fichas_venda enable row level security;

drop policy if exists "service role can manage fichas_venda" on public.fichas_venda;

create policy "service role can manage fichas_venda"
on public.fichas_venda
as permissive
for all
to service_role
using (true)
with check (true);

create extension if not exists pgcrypto;

create table if not exists public.access_codes (
  id uuid primary key default gen_random_uuid(),
  nome_responsavel text not null,
  codigo_acesso text not null unique,
  nivel_acesso text not null check (nivel_acesso in ('admin', 'consultor', 'andamento')),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_templates (
  key text primary key,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('ficha', 'document_template')),
  entity_id text not null,
  entity_label text not null,
  action text not null,
  summary text not null,
  actor_id text not null,
  actor_name text not null,
  details jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.access_codes (
  nome_responsavel,
  codigo_acesso,
  nivel_acesso,
  ativo
)
values (
  'Administrador',
  'ADMIN123',
  'admin',
  true
)
on conflict (codigo_acesso) do nothing;
